export const htmlContent = {
    "mdTestFile.md": {
        "content": "\n# Markdown syntax guide\n\n## Headers\n\n# This is a Heading h1\n\n## This is a Heading h2\n\n### This is a\n\n#### This is a Heading h4\n\n##### This is a test Heading h5\n\n###### This is a Heading h6\n\n## Emphasis\n\n_This text will be italic_  \n_This will also be italic_\n\n**This text will be bold**  \n**This will also be bold**\n\n_You **can** combine them_\n\n## Lists\n\n### Unordered\n\n- Item 1\n- Item 2\n- Item 2a\n- Item 2b\n\n### Ordered\n\n1. Item 1\n1. Item 2\n1. Item 3\n1. Item 3a\n1. Item 3b\n\n## Images\n\n![This is a alt text.](/aexol_full_logo.png 'This is a sample image.')\n\n## Links\n\nYou may be using [Markdown Live Preview](https://markdownlivepreview.com/).\n\n## Blockquotes\n\n> Markdown is a lightweight markup language with plain-text-formatting syntax, created in 2004 by John Gruber with Aaron Swartz.\n>\n> > Markdown is often used to format readme files, for writing messages in online discussion forums, and to create rich text using a plain text editor.\n\n## Tables\n\n| Syntax    | Description |\n| --------- | ----------- |\n| Header    | Title       |\n| Paragraph | Text        |\n\n## Blocks of code\n\n```\nlet message = 'Hello world';\nalert(message);\n```\n\n## Inline code\n\nThis web site is using `aexol-studio/mdtx`.\n",
        "data": {
            "link": "changelog",
            "title": "Changelog",
            "order": 99
        },
        "excerpt": ""
    },
    "basics/HowToStart.md": {
        "content": "\n# Hello world\n",
        "data": {
            "title": "How to start"
        },
        "excerpt": ""
    },
    "Changelog.md": {
        "content": "# MDtx [![NPM Version](https://img.shields.io/npm/v/mdtx.svg?style=flat)](https://www.npmjs.com/package/mdtx) [![NPM Version](https://img.shields.io/github/checks-status/aexol-studio/mdtx/main)](https://www.npmjs.com/package/mdtx) [![NPM Version](https://img.shields.io/github/last-commit/aexol-studio/mdtx)](https://github.com/aexol-studio/mdtx)\n\nInspired by generative programming and weed :). So I was learning Elm language at home usually in the evening and now I am missing all this generative stuff from Elm libs in TS.\n\n![Alt Text](sandbox/mdtx-nextjs-example/public/PresentationOfMDtx.gif)\n\n# What is MDtx?\n\n- When you add **Markdown** files with gray matter it will generate typings for those,\n- Genereted typings from **Markdowns** can get automatically convert into html structure,\n- There is **Next JS Plugin** to work faster with MDtx on NextJS,\n\n# What we serve?\n\n## [![GitHub package.json version (subfolder of monorepo)](https://img.shields.io/github/package-json/v/aexol-studio/mdtx?color=yellow&filename=%2Fpackages%2Fmdtx-cli%2Fpackage.json&label=CLI&style=for-the-badge)](https://github.com/aexol-studio/mdtx) | [![GitHub package.json version (subfolder of monorepo)](https://img.shields.io/github/package-json/v/aexol-studio/mdtx?color=green&filename=%2Fpackages%2Fmdtx-core%2Fpackage.json&label=CORE&style=for-the-badge)](https://github.com/aexol-studio/mdtx/tree/main/packages/mdtx-core) | [![GitHub package.json version (subfolder of monorepo)](https://img.shields.io/github/package-json/v/aexol-studio/mdtx?color=white&filename=%2Fpackages%2Fmdtx-plugin-nextjs%2Fpackage.json&label=NextJS-plugin&style=for-the-badge)](https://github.com/aexol-studio/mdtx/tree/main/packages/mdtx-plugin-nextjs)\n\n## Readme CLI\n\n#### Instaling MDtx\n\n```\nnpm i mdtx\n```\n\n#### Initializing MDtx\n\n```\nmdtx init\n```\n\n#### After initalize config file mdtx.json apear as that:\n\n```\n{\n  \"in\": \"./content\",\n  \"out\": \"./src\",\n}\n```\n\n- in: string - means folder with content, **(default: \"./content\")**\n- out: string - means folder to generate mdtx.ts file, **(default: \"./src\")**\n\n#### Optionally:\n\n- markdownToHtml: boolean - allow mdtx covert md content to html content. **(default: false)**\n\n#### Watch mode (on \"in\" path)\n\n```\nmdtx\n```\n\n#### Build mode (trigger once)\n\n```\nmdtx -b\n```\n\n#### [Readme CORE](https://github.com/aexol-studio/mdtx/tree/main/sandbox/mdtx-example/Readme.md)\n\n#### [Readme NextJS Plugin](https://github.com/aexol-studio/mdtx/tree/main/sandbox/mdtx-nextjs-example/Readme.md)\n\n## Roadmap\n\n- [x] NextJS plugin\n- [ ] Gatsby plugin\n- [ ] Tree building\n- [ ] Summary building\n- [ ] Other language generation\n",
        "data": {},
        "excerpt": ""
    }
} as const